name: Deploy to production
on:
  push:
    tags:
      - 'v*'
permissions:
  contents: write

jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Release to production
        run: |
          git push origin HEAD:main -f